---

name: YAML lint

"on":
  pull_request:
    branches: [main, develop]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 160
